version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: geepass
      MYSQL_DATABASE: geedb
      MYSQL_USER: geeuser
      MYSQL_PASSWORD: geepass
    ports:
      - 13306:3306
  
  gee:
    build: .
    ports:
      - 10620:10620
    depends_on:
      - mysql
    restart: always